
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    orderstatus:
        class:      Jasdero\PassePlatBundle\Services\OrderStatus
        arguments: ['@doctrine.orm.entity_manager']
    drivefolderasstatus:
        class:    Jasdero\PassePlatBundle\Services\DriveFolderAsStatus
        arguments: ['@driveconnection']
    driveconnection:
        class:    Jasdero\PassePlatBundle\Services\DriveConnection