
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    orderStatus:
        class:      Jasdero\PassePlatBundle\Services\OrderStatus
        arguments: ['@doctrine.orm.entity_manager']
